// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuangPhu.DataAccess.Data;

#nullable disable

namespace QuangPhu.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240226142728_AddImageUrlColumn")]
    partial class AddImageUrlColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuangPhu.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Book"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Book"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Book"
                        });
                });

            modelBuilder.Entity("QuangPhu.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("listPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Quang Phu",
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas consectetur fermentum justo quis tincidunt. Maecenas blandit quis nibh a malesuada. Suspendisse sed lacus massa.",
                            ISBN = "DH2354",
                            ImageUrl = "",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Fortune of Time",
                            listPrice = 99.0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Phuc Duc",
                            CategoryId = 1,
                            Description = "Donec semper eleifend odio, sed dictum lectus semper quis. In lacinia eu lectus vitae pharetra. Nulla sollicitudin ipsum quis ultrices vestibulum.",
                            ISBN = "SJ8923",
                            ImageUrl = "",
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Dark Skies",
                            listPrice = 50.0
                        },
                        new
                        {
                            Id = 3,
                            Author = "Tran Luong",
                            CategoryId = 1,
                            Description = "Nullam hendrerit ut velit sed eleifend. Duis vulputate risus nec velit finibus, porta porta felis lacinia. Ut condimentum non ex sed convallis. ",
                            ISBN = "HE335345",
                            ImageUrl = "",
                            Price = 40.0,
                            Price100 = 30.0,
                            Price50 = 35.0,
                            Title = "Sunset Sunrise",
                            listPrice = 55.0
                        },
                        new
                        {
                            Id = 4,
                            Author = "Van Lam",
                            CategoryId = 2,
                            Description = "Maecenas sollicitudin, lorem ac porta aliquet, tortor quam cursus sapien, id aliquam nisl diam bibendum nulla. Suspendisse cursus magna ut euismod egestas.",
                            ISBN = "SF32544",
                            ImageUrl = "",
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Maecenas",
                            listPrice = 49.0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Truc",
                            CategoryId = 2,
                            Description = "Fusce vitae pellentesque felis. Etiam ipsum nisl, mattis sed ligula nec, lobortis finibus justo. Etiam accumsan magna non nisl aliquet rutrum.",
                            ISBN = "HE345346",
                            ImageUrl = "",
                            Price = 60.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "Fusce vitae",
                            listPrice = 80.0
                        },
                        new
                        {
                            Id = 6,
                            Author = "Pellentesque",
                            CategoryId = 3,
                            Description = " Pellentesque urna ipsum, lacinia nec dignissim vitae, condimentum a sapien. Nam nisl sem, feugiat at varius et, vehicula bibendum leo.",
                            ISBN = "IH3438767",
                            ImageUrl = "",
                            Price = 50.0,
                            Price100 = 40.0,
                            Price50 = 45.0,
                            Title = "Fortune of Time",
                            listPrice = 70.0
                        });
                });

            modelBuilder.Entity("QuangPhu.Models.Product", b =>
                {
                    b.HasOne("QuangPhu.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
